### @name ="Register User"

POST http://localhost:8080/auth/register
Content-Type: application/json
Accept: application/json

{
  "email": "peter@visa.com",
  "password": "secret",
  "username": "Peter",
  "roles": [ {
    "name": "ROLE_USER",
    "description": "Has basic rights"
  }]
}

### @name ="Register Admin"

POST http://localhost:8080/auth/register
Content-Type: application/json
Accept: application/json

{
  "email": "anna@visa.com",
  "password": "secret",
  "username": "Anna",
  "roles": [ {
  "name": "ROLE_USER",
  "description": "Has basic rights"
},
    {
      "name": "ROLE_ADMIN",
      "description": "Admin rights"
    }]
}


### @name ="Admin Login"

POST http://localhost:8080/auth/login
Content-Type: application/json
Accept: application/json

{
  "email": "anna@visa.com",
  "password": "secret"
}



### @name ="User Login"

POST http://localhost:8080/auth/login
Content-Type: application/json
Accept: application/json

{
  "email": "peter@visa.com",
  "password": "secret"
}

### @name="access Protected Resource"

GET http://localhost:8080/api/products
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJwZXRlckB2aXNhLmNvbSIsImlhdCI6MTc3Mzk4ODcyNywiZXhwIjoxNzczOTkwMTY3LCJhdXRob3JpdGllcyI6WyJST0xFX1VTRVIiXSwiaXNzIjoiaHR0cHM6Ly9zZXJ2ZXIudmlzYS5jb206NDQxIn0.JiwbvX3X1f2tLlx7vCzUl006aJtPkgEPFmExuxZCEMs


### @name="access Protected Admin Resource"
GET http://localhost:8080/api/orders/report
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhbm5hQHZpc2EuY29tIiwiaWF0IjoxNzczOTg5MjY5LCJleHAiOjE3NzM5OTA3MDksImF1dGhvcml0aWVzIjpbIlJPTEVfVVNFUiIsIlJPTEVfQURNSU4iXSwiaXNzIjoiaHR0cHM6Ly9zZXJ2ZXIudmlzYS5jb206NDQxIn0.JVahrQkMLGMv0wSre2FHESfg618kQPVqhubkpglRYA0
