### @name ="Register User"

POST http://localhost:8080/auth/register
Content-Type: application/json
Accept: application/json

{
  "email": "peter@visa.com",
  "password": "secret",
  "username": "Peter",
  "roles": [ {
    "name": "ROLE_USER",
    "description": "Has basic rights"
  }]
}

### @name ="Register Admin"

POST http://localhost:8080/auth/register
Content-Type: application/json
Accept: application/json

{
  "email": "anna@visa.com",
  "password": "secret",
  "username": "Anna",
  "roles": [ {
  "name": "ROLE_USER",
  "description": "Has basic rights"
},
    {
      "name": "ROLE_ADMIN",
      "description": "Admin rights"
    }]
}


### @name ="Admin Login"

POST http://localhost:8080/auth/login
Content-Type: application/json
Accept: application/json

{
  "email": "anna@visa.com",
  "password": "secret"
}


### @name="access Protected Resource"

GET http://localhost:8080/api/products
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhbm5hQHZpc2EuY29tIiwiaWF0IjoxNzczOTgxMzE3LCJleHAiOjE3NzM5ODI3NTcsImF1dGhvcml0aWVzIjpbIlJPTEVfVVNFUiIsIlJPTEVfQURNSU4iXSwiaXNzIjoiaHR0cHM6Ly9zZXJ2ZXIudmlzYS5jb206NDQxIn0.5cvF61DKn_WZHO5g8vvK4Ao826dC8n_Snaea-_aALUQ
